# This file defines the contenttypes on the website. See the documentation for
# details: http://docs.bolt.cm/content#defining-contenttypes

# Pages can be used for the more 'static' pages on your site. Things like
# 'about us', 'contact' or a 'disclaimer'. This content-type has a 'templateselect'
# field, which allows you to override the record_template setting for an
# individual page.
# The taxonomy for this contenttype is defined as 'chapters', which is a so-called
# "grouping taxonomy". This way you can easily group sets of pages that logically
# belong together. If your site has a 'services' section, in which you'd like to
# list the different types of services a company provides, you can group these
# together.

pages:
    name: Pages
    singular_name: Page
    default_status: published
    singular_slug: page
    icon_many: "fa:file-text-o"
    icon_one: "fa:file-text-o"
    fields:
        title:
            type: text
            class: large
            group: content

        slug:
            type: slug
            uses: title
        template:
            type: templateselect
            filter: '*.twig'
        description:
            type: textarea
            label: Meta description
            group: SEO
            height: 100px
        keywords:
            type: textarea
            label: Meta keywords
            height: 100px

    recordsperpage: 100

programs:
    name: Программы
    singular_name: Программа
    slug: programs
    singular_slug: programs
    default_status: published
    sort: +sortorder
    fields:
        sortorder:
            type: integer
            label: Сортировка
        title:
            type: text
            label: Название
            required: true

        slug:
            type: slug
            uses: title

        type:
            type: select
            label: Тип
            required: true
            values:
              - Для детей
              - Для подростков
              - Для взрослых
        image:
            type: image
            label: Изображение
            required: true
        body:
            type: markdown
            label: Описание программы
            required: true

schedule_records:
    name: Расписание
    singular_name: Расписание
    slug: schedule-records
    default_status: published
    viewless: true
    icon_many: "fa:calendar"
    icon_one: "fa:calendar"

    fields:
        timefrom:
            type: text
            variant: inline
            label: Начало
            pattern: "(0[0-9]|1[0-9]|2[0-3])(:[0-5][0-9])"
            info: Формат: 08:59
            required: true

        timeto:
            type: text
            variant: inline
            label: Окончание
            pattern: "(0[0-9]|1[0-9]|2[0-3])(:[0-5][0-9])"
            info: Формат: 08:59
            required: true

        day:
            type: select
            label: День
            values: [Понедельник, Вторник, Среда, Четверг, Пятница, Суббота, Воскресенье]
            required: true

        program:
            type: select
            label: Программа
            required: true
            values: programs/title
            autocomplete: true

        note:
            type: text
            variant: inline
            label: Примечание
            info: Будет выводиться в скобках

tutors:
    name: Преподаватели
    singular_name: Преподаватель
    slug: tutors
    singular_slug: tutors
    default_status: published
    viewless: false
    icon_many: "fa:users"
    icon_one: "fa:user"

    fields:

        title:
            group: Content
            type: text
            label: Имя преподавателя
            variant: inline
            required: true

        slug:
            type: slug
            uses: title

        image:
            type: image
            label: Фото
            required: true

        body:
            type: markdown
            label: Описание
            required: true

about:
    name: О нас
    singular_name: О нас
    slug: about
    singular_slug: about
    default_status: published
    viewless: false

    fields:

        title:
            group: Content
            type: text
            label: Заголовок
            variant: inline
            required: true

        slug:
            type: slug
            uses: title

        image:
            type: image
            label: Фото
            required: true

        body:
            type: markdown
            label: Содержимое
            required: true

gallery:
    name: Галлереи
    singular_name: Галлерея
    slug: gallery
    singular_slug: gallery
    default_status: published
    viewless: false
    record_template: 'record-gallery.twig'
    icon_many: "fa:camera"
    icon_one: "fa:camera"
    fields:
        title:
            group: Content
            type: text
            label: Заголовок
            variant: inline
            required: true
        slug:
            type: slug
            uses: title

        image:
            type: imagelist
            label: Изображения
            required: true







# Entries can be used for things like 'news' or 'blogpostings'. They have a 'teaser',
# which can be used for a short blurb on listing-pages, allowing visitors to
# click-through to the rest of the entry. It also has fields for an image and an
# optional video.
# A relation is defined to the pages contenttype. This way you can refer to a page
# from your news-item.
# This contenttype defines 'categories' and 'tags' as taxonomies, allowing the
# editor to use both to categorize a specific entry.
# The 'sort' is set to '-datepublish', which means that newer entries will be
# shown above older entries.


# Using YAML repeated nodes
#
# YAML allows the defining of "repeated nodes". These allow you to define a 'node'
# with a 'key: &name' and referenced later with '<<: *name'
#
# Bolt allows you to define this with the special entry of '__nodes:' that itself 
# won't create a Contenttype, but will allow you to use it in actual contenttypes
# to prevent repeating yourself.
#
# To achieve this, first create a key '__nodes:' 
#__nodes:
#    field_defaults: &field_defaults
#        title:
#            type: text
#            class: large
#            group: main
#        slug:
#            type: slug
#            uses: title
#    template_defaults: &template_defaults
#        template:
#            type: templateselect
#            filter: '*.twig'
#            group: meta
#
# Then, as an example, you could create a Contenttype with default fields, with 
# an additional 'image' field.
#
#contenttype_abc:
#    name: Contenttype Abc
#    fields:
#        <<: *field_defaults
#        image:
#            type: image
#            attrib: title
#            extensions: [ gif, jpg, png ]
#        <<: *template_defaults
#    taxonomy: [ chapters ]
#    recordsperpage: 10
#
# Alternatively, or additionally, you then can thencreate a Contenttype with 
# default fields, and a 'select' field, and a different 'templateselect' option.
#
#contenttype_xyz:
#    name: Contenttype Xyz
#    fields:
#        <<: *field_defaults
#        selectfield:
#            type: select
#            values: [ none, foo, bar ]
#        template:
#            type: templateselect
#            filter: '*_xyz.twig'
#    taxonomy: [ tags ]
#    recordsperpage: 20

# Possible field types:
#
# text - varchar(256) - input type text.
# integer - integer - Input field for integer numbers.
# float - double - Input field for floating numbers, stored as 'Double'.
# geolocation - text (65kb) - Input field for geolocation. Enter an address, and the location is geocoded to latitude/longitude coordinates
# imagelist - text (65kb) - Input type for imagelists. Add multiple images with a description. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# filelist - text (65kb) - Input type for a list of files. Including a description.
# video - varchar(256) - Video embed widget, stored as filename.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# markdown - varchar(32768) - Simple, plain < textarea > field, which is parsed as Markdown text.
# datetime - datetime - date and time selector widget.
# date - datetime - date selector widget.
# select - varchar(256) - select with predefined values
# templateselect - varchar(256) - select with template filenames
# checkbox - integer - checkbox-field which is 1 (checked) or 0 (unchecked)

# number (deprecated) - input type decimal(18,9), useful for storing number that need to be sortable